# Generated by Django 2.1 on 2018-12-06 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='my_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_description', models.CharField(max_length=300)),
                ('file_link', models.CharField(max_length=500)),
                ('date_of_file_upload', models.DateTimeField(auto_now_add=True)),
                ('file_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('date_held', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ministry_or_church', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='my_upload',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s_uploads', to='ebc_app.Serie'),
        ),
        migrations.AddField(
            model_name='my_upload',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='ebc_app.Speaker'),
        ),
    ]
